Repository boostcampwm-2022/iOS06-NearTalk, pull requests merged in 2022-12, with the labels that each got.

#121 [메인지도] Rx로 지도 뷰 이벤트 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Data/Repositories/DefaultAccessibleChatRoomsRepository.swift
  NearTalk/NearTalk/Domain/Entities/NCLocation.swift
  NearTalk/NearTalk/Domain/Entities/NCMapRegion.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/AccessibleChatRoomsRepository.swift
  NearTalk/NearTalk/Domain/UseCases/FetchAccessibleChatRoomsUseCase.swift
  NearTalk/NearTalk/Presentation/MainMap/Coordinator/MainMapCoordinator.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/Annotations/ChatRoomAnnotation.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/BottomSheet/BottomSheetTableViewCell/BottomSheetTableViewCell.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/BottomSheet/BottomSheetViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/View/MainMapViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/ViewModel/MainMapViewModel.swift
  NearTalk/NearTalk/Resource/Info.plist
Labels: feature, refactor, fix

#120 [마이프로필, 프로필 수정, 로그인, 온보딩, 앱설정 화면] 화면 UI 및 키보드 푸쉬 이벤트 처리 개선
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/AppDelegate.swift
  NearTalk/NearTalk/Presentation/AppSetting/View/AppSettingTableViewCell.swift
  NearTalk/NearTalk/Presentation/AppSetting/View/AppSettingViewController.swift
  NearTalk/NearTalk/Presentation/AppSetting/ViewModel/AppSettingViewModel.swift
  NearTalk/NearTalk/Presentation/Login/View/LoginViewController.swift
  NearTalk/NearTalk/Presentation/MyProfile/View/MyProfileViewController.swift
  NearTalk/NearTalk/Presentation/Onboarding/View/OnboardingView.swift
  NearTalk/NearTalk/Presentation/Onboarding/View/OnboardingViewController.swift
  NearTalk/NearTalk/Presentation/Onboarding/View/OnboardingViewPreview.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/View/ProfileSettingView.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/View/ProfileSettingViewController.swift
  NearTalk/NearTalk/Presentation/TabBar/Coordinator/RootTabBarCoordinator.swift
Labels: refactor, fix

#122 [친구목록] UI개선, 자동 업데이트 기능 추가
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/DIContainer/ChatRoomListDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/ChatRoomListRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatRoomListRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultProfileRepository.swift
  NearTalk/NearTalk/Domain/UseCases/FetchChatRoomUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/FetchFriendListUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/FetchChatRoomInfoUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/UserDefaultUseCase.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/Coordinator/ChatRoomListCoordinator.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListCell.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListViewController.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/ViewModel/ChatRoomListViewModel.swift
  NearTalk/NearTalk/Presentation/FriendList/View/FriendListCell.swift
  NearTalk/NearTalk/Presentation/FriendList/View/FriendViewController.swift
  NearTalk/NearTalk/Presentation/FriendList/ViewModel/FriendListViewModel.swift
Labels: bug, feature, fix

#126 [회원 탈퇴, 로그인] 회원 탈퇴 및 로그인 후 메인화면으로 넘어가는 버그 픽스
  NearTalk/NearTalk/Application/DIContainer/AppSettingDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/LoginDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/DefaultAuthRepository.swift
  NearTalk/NearTalk/Data/Repositories/DummyAuthRepository.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/AuthRepository.swift
  NearTalk/NearTalk/Domain/UseCases/DropOutUseCase.swift
  NearTalk/NearTalk/Infrastructure/Network/AuthService.swift
  NearTalk/NearTalk/Infrastructure/Network/FirebaseAuthService.swift
  NearTalk/NearTalk/Presentation/AppSetting/Coordinator/AppSettingCoordinator.swift
  NearTalk/NearTalk/Presentation/AppSetting/View/AppSettingViewController.swift
  NearTalk/NearTalk/Presentation/AppSetting/ViewModel/AppSettingViewModel.swift
  NearTalk/NearTalk/Presentation/Login/ViewModel/LoginViewModel.swift
Labels: feature, fix

#127 [채팅] 채팅화면 UI 개선 및 채팅방 입장 후 로직 추가
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/DIContainer/ChatDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/ProfileDetailDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/ChatRoomListRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatRoomListRepository.swift
  NearTalk/NearTalk/Domain/UseCases/FetchChatRoomUseCase.swift
  NearTalk/NearTalk/Infrastructure/Network/RealTimeDatabaseService.swift
  NearTalk/NearTalk/Presentation/Chat/EnterChatRoomUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/FetchChatRoomInfoUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/MessagingUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatCollectionViewCell.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatViewController.swift
  NearTalk/NearTalk/Presentation/Chat/View/chatInputAccessoryView.swift
  NearTalk/NearTalk/Presentation/Chat/ViewModel/ChatViewModel.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/Coordinator/CreateGroupChatCoordinator.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/Coordinator/ProfileDetailCoordinator.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/FetchProfileUseCase.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/View/ProfileDetailViewController.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/ViewModel/ProfileDetailViewModel.swift
Labels: feature, fix

#129 [프로필 수정 > 업로드 로딩] 수정한 프로필 서버에 업로드 중 로딩 기능 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  NearTalk/NearTalk/Presentation/Onboarding/View/OnboardingViewPreview.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/Coordinator/ProfileSettingCoordinator.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/View/ProfileSettingView.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/View/ProfileSettingViewController.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/View/UploadingIndicatorViewController.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/ViewModel/ProfileSettingViewModel.swift
Labels: feature, refactor

#130 [메인지도] BottomSheet 셀 구현 및 현재 위치 저장
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Data/Repositories/DefaultAccessibleChatRoomsRepository.swift
  NearTalk/NearTalk/Infrastructure/Extensions/MKMapView+Rx/MKMapView+Rx.swift
  NearTalk/NearTalk/Infrastructure/Extensions/MKMapView+Rx/RxMKMapViewDelegateProxy.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/BottomSheet/BottomSheetTableViewCell/BottomSheetTableViewCell.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/BottomSheet/BottomSheetViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/View/MainMapViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/ViewModel/MainMapViewModel.swift
Labels: feature

#136 [앱설정>Color 등록] Dynamic Color Asset에 등록 및 Static으로 정의
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Infrastructure/Utils/ColorSet.swift
  NearTalk/NearTalk/Resource/Assets.xcassets/label.colorset/Contents.json
  NearTalk/NearTalk/Resource/Assets.xcassets/primaryBackground.colorset/Contents.json
  NearTalk/NearTalk/Resource/Assets.xcassets/primaryColor.colorset/Contents.json
  NearTalk/NearTalk/Resource/Assets.xcassets/secondaryBackground.colorset/Contents.json
  NearTalk/NearTalk/Resource/Assets.xcassets/secondaryLabel.colorset/Contents.json
  NearTalk/NearTalk/Resource/Assets.xcassets/seperatorColor.colorset/Contents.json
  NearTalk/NearTalk/Resource/Assets.xcassets/tertiaryLabel.colorset/Contents.json
  NearTalk/NearTalk/Resource/Assets.xcassets/whiteLabel.colorset/Contents.json
Labels: feature

#144 [로그인>로그인 버튼] 애플 로그인 완료 후 앱 전환 직전까지 로그인 버튼 비활성화 처리
  NearTalk/NearTalk/Presentation/Login/View/LoginViewController.swift
  NearTalk/NearTalk/Presentation/Login/ViewModel/LoginViewModel.swift
Labels: refactor, fix

#143 [온보딩>UI] 온보딩 화면 신형 UI로 업데이트
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Infrastructure/Extensions/UIViewController+KeyboardHandler.swift
  NearTalk/NearTalk/Presentation/Onboarding/View/OnboardingView.swift
  NearTalk/NearTalk/Presentation/Onboarding/View/OnboardingViewController.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/View/ProfileSettingViewController.swift
Labels: refactor

#148 [프로필 수정, 온보딩 리팩토링] 뷰 공용화, 리팩토링, 버그 픽스
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/DIContainer/ProfileSettingDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/DefaultMediaRepository.swift
  NearTalk/NearTalk/Data/Repositories/DummyProfileRepository.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/MediaRepository.swift
  NearTalk/NearTalk/Infrastructure/Utils/PhotoImagePickerViewController.swift
  NearTalk/NearTalk/Infrastructure/Utils/UserProfileInputView.swift
  NearTalk/NearTalk/Infrastructure/Utils/UserProfileInputViewController.swift
  NearTalk/NearTalk/Presentation/MyProfile/View/MyProfileView.swift
  NearTalk/NearTalk/Presentation/MyProfile/View/MyProfileViewController.swift
  NearTalk/NearTalk/Presentation/MyProfile/ViewModel/MyProfileViewModel.swift
  NearTalk/NearTalk/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  NearTalk/NearTalk/Presentation/Onboarding/View/OnboardingViewController.swift
  NearTalk/NearTalk/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/Coordinator/ProfileSettingCoordinator.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/View/ProfileSettingView.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/View/ProfileSettingViewController.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/View/UploadingIndicatorViewController.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/ViewModel/ProfileSettingViewModel.swift
Labels: bug, refactor, fix

#146 [채팅방목록] 채팅방 목록 UI개선 및 현재 사용자위치와 채팅방 거리에따른 입장여부 판별
  NearTalk/GPSPoints/textMoveGPS.gpx
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Domain/Entities/ChatRoomList.swift
  NearTalk/NearTalk/Domain/Entities/NCLocation.swift
  NearTalk/NearTalk/Domain/UseCases/FetchChatRoomUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/UserDefaultUseCase.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/Coordinator/ChatRoomListCoordinator.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListCell.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListViewController.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/ViewModel/ChatRoomListViewModel.swift
  NearTalk/NearTalk/Presentation/FriendList/View/FriendListCell.swift
  NearTalk/NearTalk/Presentation/FriendList/View/FriendViewController.swift
  NearTalk/NearTalk/Resource/Assets.xcassets/ChatLogo.imageset/ChatLogo.png
  NearTalk/NearTalk/Resource/Assets.xcassets/ChatLogo.imageset/Contents.json
  NearTalk/NearTalk/Resource/Assets.xcassets/Logo.imageset/Contents.json
  NearTalk/NearTalk/Resource/Assets.xcassets/Logo.imageset/Logo.png
  NearTalk/NearTalk/Resource/Assets.xcassets/nearTalkLogo.imageset/Contents.json
  NearTalk/NearTalk/Resource/Assets.xcassets/nearTalkLogo.imageset/nearTalkLogo.png
  images/ChatLogo.png
  images/Logo.png
  images/nearTalkLogo.png
Labels: bug, feature, fix

#150 [메인지도] Coordinator를 이용한 채팅방 관련 화면전환 구현
  NearTalk/NearTalk/Application/DIContainer/MainMapDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/DefaultAccessibleChatRoomsRepository.swift
  NearTalk/NearTalk/Infrastructure/Extensions/MKMapView+Rx/MKMapView+Rx.swift
  NearTalk/NearTalk/Infrastructure/Extensions/MKMapView+Rx/RxMKMapViewDelegateProxy.swift
  NearTalk/NearTalk/Presentation/MainMap/Coordinator/MainMapCoordinator.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/BottomSheet/BottomSheetTableViewCell/BottomSheetTableViewCell.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/BottomSheet/BottomSheetViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/View/MainMapViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/ViewModel/MainMapViewModel.swift
Labels: feature, refactor, fix

#154 [채팅] UI 개선 및 버그 수정
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Presentation/Chat/EnterChatRoomUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/MessageItem.swift
  NearTalk/NearTalk/Presentation/Chat/UserDefaultUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatCollectionViewCell.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatViewController.swift
  NearTalk/NearTalk/Presentation/Chat/View/chatInputAccessoryView.swift
  NearTalk/NearTalk/Presentation/Chat/ViewModel/ChatViewModel.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/View/GroupChatCreationViewController.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/ViewModel/CreateGroupChatViewModel.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/FetchProfileUseCase.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/View/ProfileDetailViewController.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/ViewModel/ProfileDetailViewModel.swift
Labels: feature, fix

#160 [Fix] 로그아웃 후 로그인 화면으로 안넘어가는 버그 픽스
  NearTalk/NearTalk/Application/Coordinator/AppCoordinator.swift
  NearTalk/NearTalk/Presentation/TabBar/Coordinator/RootTabBarCoordinator.swift
Labels: fix

#161 [친구 프로필] 친구 프로필 수정 기능 추가
  NearTalk/NearTalk/Data/Repositories/DefaultProfileRepository.swift
  NearTalk/NearTalk/Data/Repositories/Dummy/DummyProfileRepository.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/ProfileRepository.swift
  NearTalk/NearTalk/Domain/UseCases/UpdateProfileUseCase.swift
Labels: feature

#168 [DM] DM기능 추가했습니다.
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/DIContainer/ChatRoomListDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/ProfileDetailDIContainer.swift
  NearTalk/NearTalk/Domain/DTO/ChatRoomList.swift
  NearTalk/NearTalk/Domain/UseCases/FetchChatRoomUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/UpdateProfileUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatViewController.swift
  NearTalk/NearTalk/Presentation/Chat/View/chatInputAccessoryView.swift
  NearTalk/NearTalk/Presentation/Chat/ViewModel/ChatViewModel.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListCell.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListViewController.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/ViewModel/ChatRoomListViewModel.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/View/GroupChatCreationViewController.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/ViewModel/CreateGroupChatViewModel.swift
  NearTalk/NearTalk/Presentation/FriendList/View/FriendListCell.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/Coordinator/ProfileDetailCoordinator.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/FetchProfileUseCase.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/View/ProfileDetailViewController.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/ViewModel/ProfileDetailViewModel.swift
  NearTalk/NearTalk/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon1024x1024.png
  NearTalk/NearTalk/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: feature

#170 [채팅] 채팅 텍스트 입력시 입력란 높이 조절되도록 구현
  NearTalk/Cartfile.resolved
  NearTalk/NearTalk/Presentation/Chat/View/ChatCollectionViewCell.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatViewController.swift
  NearTalk/NearTalk/Presentation/Chat/View/chatInputAccessoryView.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/View/ProfileDetailViewController.swift
Labels: feature

#172 [앱설정] 탈퇴 시, 가입한 채팅 방 및 친구 프로필에서 유저 uuid 제거, 닉네임 정책 변경
  NearTalk/NearTalk/Application/DIContainer/AppSettingDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/MyProfileDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/ChatRoomListRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatRoomListRepository.swift
  NearTalk/NearTalk/Domain/UseCases/DropOutUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/ValidateUseCase.swift
  NearTalk/NearTalk/Presentation/AppSetting/ViewModel/AppSettingViewModel.swift
  NearTalk/NearTalk/Presentation/Login/View/LoginViewController.swift
Labels: feature

#171 [채팅방] 메세지 페이지네이션 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Data/Repositories/DefaultChatMessageRepository.swift
  NearTalk/NearTalk/Domain/UseCases/Dummy/DummyVerifyUseCase.swift
  NearTalk/NearTalk/Infrastructure/Network/FCMService.swift
  NearTalk/NearTalk/Infrastructure/Network/RealTimeDatabaseService.swift
  NearTalk/NearTalk/Presentation/Chat/EnterChatRoomUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/FetchChatRoomInfoUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/MessagingUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/UserDefaultUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatCollectionViewCell.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatViewController.swift
  NearTalk/NearTalk/Presentation/Chat/View/chatInputAccessoryView.swift
  NearTalk/NearTalk/Presentation/Chat/ViewModel/ChatViewModel.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListCell.swift
  NearTalk/NearTalk/Presentation/FriendList/ViewModel/FriendListViewModel.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/FetchProfileUseCase.swift
Labels: feature

#174 [메인지도 > UI] 현재 위치 트래킹, 채팅방 입장가능 설정, 채팅방 기준 원형 overlay
  NearTalk/NearTalk/Domain/DTO/NCLocation.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/ViewModel/CreateGroupChatViewModel.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/Annotations/ChatRoomAnnotation.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/Annotations/GroupChatRoomAnnotationView.swift
  NearTalk/NearTalk/Presentation/MainMap/View/MainMapViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/ViewModel/MainMapViewModel.swift
Labels: feature, fix

#179 [채팅 생성] 채팅 생성에 필요한 데이터 수정
  NearTalk/NearTalk/Presentation/Chat/View/ChatCollectionViewCell.swift
  NearTalk/NearTalk/Presentation/Chat/ViewModel/ChatViewModel.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/View/GroupChatCreationViewController.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/View/RangeZoneView.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/ViewModel/CreateGroupChatViewModel.swift
Labels: bug, feature

#176 [프로필 수정, 온보딩 화면] 상태메세지 입력 텍스트 필드에서 텍스트 뷰로 변경
  NearTalk/NearTalk/Domain/UseCases/ValidateUseCase.swift
  NearTalk/NearTalk/Infrastructure/Utils/UserProfileInputView.swift
  NearTalk/NearTalk/Infrastructure/Utils/UserProfileInputViewController.swift
  NearTalk/NearTalk/Presentation/Onboarding/View/OnboardingViewController.swift
  NearTalk/NearTalk/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/View/ProfileSettingViewController.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/ViewModel/ProfileSettingViewModel.swift
Labels: feature, fix

#184 [Fix] 프로필 등록, 수정 안되는 이슈 해결
  NearTalk/NearTalk/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/ViewModel/ProfileSettingViewModel.swift
Labels: fix

#183 [메인지도 > UI개선] 사용자 현재 위치 표시 View 구현
  NearTalk/NearTalk/Application/Coordinator/AppCoordinator.swift
  NearTalk/NearTalk/Application/SceneDelegate.swift
  NearTalk/NearTalk/Data/Repositories/DefaultAccessibleChatRoomsRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatMessageRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatRoomListRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultProfileRepository.swift
  NearTalk/NearTalk/Data/Repositories/Dummy/DummyAuthRepository.swift
  NearTalk/NearTalk/Data/Repositories/Dummy/DummyProfileRepository.swift
  NearTalk/NearTalk/Domain/UseCases/FetchChatRoomUseCase.swift
  NearTalk/NearTalk/Infrastructure/Coredata/CoreDataService.swift
  NearTalk/NearTalk/Infrastructure/Extensions/Codable+Dictionary.swift
  NearTalk/NearTalk/Infrastructure/Extensions/MKMapView+Rx/MKMapView+Rx.swift
  NearTalk/NearTalk/Infrastructure/Extensions/UIImage+Resize.swift
  NearTalk/NearTalk/Infrastructure/Extensions/UIViewController+KeyboardHandler.swift
  NearTalk/NearTalk/Infrastructure/Network/FCMService.swift
  NearTalk/NearTalk/Infrastructure/Network/FirebaseAuthService.swift
  NearTalk/NearTalk/Infrastructure/Network/FirestoreService.swift
  NearTalk/NearTalk/Infrastructure/Network/RealTimeDatabaseService.swift
  NearTalk/NearTalk/Infrastructure/Network/StorageService.swift
  NearTalk/NearTalk/Infrastructure/UserDefaults/UserDefaultsService.swift
  NearTalk/NearTalk/Infrastructure/Utils/Environment.swift
  NearTalk/NearTalk/Presentation/Chat/EnterChatRoomUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatViewController.swift
  NearTalk/NearTalk/Presentation/Chat/ViewModel/ChatViewModel.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/Coordinator/ChatRoomListCoordinator.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListCell.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListViewController.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/Coordinator/CreateGroupChatCoordinator.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/ViewModel/CreateGroupChatViewModel.swift
  NearTalk/NearTalk/Presentation/FriendList/Coordinator/FriendListCoordinator.swift
  NearTalk/NearTalk/Presentation/FriendList/View/FriendViewController.swift
  NearTalk/NearTalk/Presentation/LaunchScreen/ViewModel/LaunchScreenViewModel.swift
  NearTalk/NearTalk/Presentation/MainMap/Coordinator/MainMapCoordinator.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/Annotations/CalloutView.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/Annotations/ChatRoomAnnotation.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/Annotations/ChatRoomClusterAnnotationView.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/Annotations/GroupChatRoomAnnotationView.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/BottomSheet/BottomSheetTableViewCell/BottomSheetTableViewCell.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/BottomSheet/BottomSheetViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/View/MainMapViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/ViewModel/MainMapViewModel.swift
  NearTalk/NearTalk/Presentation/MyProfile/ViewModel/MyProfileViewModel.swift
  NearTalk/NearTalk/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/Coordinator/ProfileDetailCoordinator.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/ViewModel/ProfileDetailViewModel.swift
  NearTalk/NearTalk/Presentation/TabBar/Coordinator/RootTabBarCoordinator.swift
Labels: feature, chore, refactor, fix

#186 [탈퇴] 탈퇴 시 Realtime DB에 있는 유저 티켓 제거
  NearTalk/NearTalk/Data/Repositories/DefaultChatRoomListRepository.swift
  NearTalk/NearTalk/Infrastructure/Network/RealTimeDatabaseService.swift
Labels: fix

#190 [DM, 탭바] 탭바 안 읽은 메세지 표시, 버그 수정
  NearTalk/NearTalk/Application/DIContainer/ProfileDetailDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/RootTabBarDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/ChatRoomListRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatRoomListRepository.swift
  NearTalk/NearTalk/Domain/UseCases/FetchChatRoomUseCase.swift
  NearTalk/NearTalk/Infrastructure/Network/RealTimeDatabaseService.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatViewController.swift
  NearTalk/NearTalk/Presentation/Chat/ViewModel/ChatViewModel.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListCell.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/ViewModel/ProfileDetailViewModel.swift
  NearTalk/NearTalk/Presentation/TabBar/View/RootTabBarController.swift
  NearTalk/NearTalk/Presentation/TabBar/ViewModel/RootTabBarViewModel.swift
  images/nearTalkLogo.png
Labels: bug, feature

#193 [메세지 캐싱] 코어데이터를 활용한 메세지 캐싱 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/DIContainer/ChatDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/ChatRoomListDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatMessageRepository.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/ChatMessageRepository.swift
  NearTalk/NearTalk/Infrastructure/Coredata/CDChatMessage+CoreDataClass.swift
  NearTalk/NearTalk/Infrastructure/Coredata/CDChatMessage+CoreDataProperties.swift
  NearTalk/NearTalk/Infrastructure/Coredata/CDChatRoom+CoreDataClass.swift
  NearTalk/NearTalk/Infrastructure/Coredata/CDChatRoom+CoreDataProperties.swift
  NearTalk/NearTalk/Infrastructure/Coredata/CDUserChatRoomTicket+CoreDataClass.swift
  NearTalk/NearTalk/Infrastructure/Coredata/CDUserChatRoomTicket+CoreDataProperties.swift
  NearTalk/NearTalk/Infrastructure/Coredata/CDUserProfile+CoreDataClass.swift
  NearTalk/NearTalk/Infrastructure/Coredata/CDUserProfile+CoreDataProperties.swift
  NearTalk/NearTalk/Infrastructure/Coredata/CoreDataEntityKey.swift
  NearTalk/NearTalk/Infrastructure/Coredata/CoreDataService.swift
  NearTalk/NearTalk/Infrastructure/Coredata/NearTalk.xcdatamodeld/NearTalk.xcdatamodel/contents
  NearTalk/NearTalk/Presentation/Chat/MessagingUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatViewController.swift
  NearTalk/NearTalk/Presentation/Chat/ViewModel/ChatViewModel.swift
  NearTalk/NearTalkTests/Infrastructure/CoreDataTests.swift
Labels: feature

#194 [Fix] 특정 유저의 특정 채팅방 티켓 구독
  NearTalk/NearTalk/Application/DIContainer/RootTabBarDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/ChatRoomListRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatRoomListRepository.swift
  NearTalk/NearTalk/Infrastructure/Network/RealTimeDatabaseService.swift
  NearTalk/NearTalk/Presentation/Chat/FetchChatRoomInfoUseCase.swift
Labels: bug

#197 [채팅방, 탭바] 채팅방 탈퇴 기능 구현 및 탭바 UI 버그 수정
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/DIContainer/ChatDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/ChatRoomListRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatRoomListRepository.swift
  NearTalk/NearTalk/Infrastructure/Network/RealTimeDatabaseService.swift
  NearTalk/NearTalk/Presentation/Chat/DropChatRoomUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatViewController.swift
  NearTalk/NearTalk/Presentation/Chat/ViewModel/ChatViewModel.swift
  NearTalk/NearTalk/Presentation/TabBar/Coordinator/RootTabBarCoordinator.swift
Labels: feature, fix

#202 [프로필 수정, 온보딩] 색상 버그 픽스
  NearTalk/NearTalk/Infrastructure/Utils/UserProfileInputView.swift
  NearTalk/NearTalk/Infrastructure/Utils/UserProfileInputViewController.swift
Labels: fix

#207 [채팅] 내가 채팅방에 입장한 이후에 첫 입장한 찬가자 이미지/이름 데이터 안 불러와지는 버그 해결
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Data/Repositories/DefaultProfileRepository.swift
  NearTalk/NearTalk/Domain/DTO/MessageItem.swift
  NearTalk/NearTalk/Domain/UseCases/DropChatRoomUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/EnterChatRoomUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/FetchChatRoomInfoUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/MessagingUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/UserDefaultUseCase.swift
  NearTalk/NearTalk/Infrastructure/Network/FCMService.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatCollectionViewCell.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatViewController.swift
  NearTalk/NearTalk/Presentation/Chat/ViewModel/ChatViewModel.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/View/ProfileDetailViewController.swift
Labels: fix

#208 [Docs] 프로젝트 소개 추가
  README.md
Labels: chore

#209 [README.md] README.md 업데이트
  README.md
Labels: chore
