Repository boostcampwm-2022/iOS06-NearTalk, pull requests merged in 2022-11, with the labels that each got.

#59 LaunchScreen 베이스 Coordinator 작성
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/Coordinator/AppCoordinator.swift
  NearTalk/NearTalk/Application/Coordinator/LaunchScreenCoordinator.swift
  NearTalk/NearTalk/Application/DIContainer/LaunchScreenDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/DefaultLaunchScreenRepository.swift
  NearTalk/NearTalk/Domain/UseCases/LaunchScreenUseCase.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/Coordinator/LaunchScreenCoordinator.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/View/LaunchScreenRepository.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/View/LaunchScreenViewController.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/ViewModel/LaunchScreenViewModel.swift
Labels: feature

#54 [로그인>UI구현] AuthenticationServices를 활용한 애플 로그인 기본 UI 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Presentation/Login/View/LoginViewController.swift
Labels: feature

#55 [프로필 수정>프로필 설정 UI 구현] 프로필 설정 기본 UI 화면 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Presentation/ProfileSetting/View/ProfileSettingViewController.swift
Labels: feature

#56 [앱 설정>마이페이지 설정 UI 구현] 앱 설정 UI 기본 화면 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Presentation/AppSetting/View/AppSettingTableViewCell.swift
  NearTalk/NearTalk/Presentation/AppSetting/View/AppSettingViewController.swift
Labels: feature

#57 [온보딩>UI구현] 온보딩 UI 기본 화면 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Presentation/Onboarding/View/OnboardingViewController.swift
Labels: feature

#58 [마이페이지>프로필 화면 UI 구현] 마이페이지 프로필 화면 UI 기본 화면 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Presentation/MyProfile/View/MyProfileViewController.swift
Labels: feature

#53 [메인지도>초기 지도화면] MKMapView를 이용한 지도 화면 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk.xcodeproj/xcshareddata/xcschemes/NearTalk.xcscheme
  NearTalk/NearTalk/Application/SceneDelegate.swift
  NearTalk/NearTalk/Presentation/MainMap/Coordinator/MainMapCoordinator.swift
  NearTalk/NearTalk/Presentation/MainMap/View/MainMapViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/ViewModel/MainMapViewModel.swift
  NearTalk/NearTalk/Resource/Info.plist
Labels: feature

#52 [채팅방목록>UI구현] 채팅방 목록 기본 UI를 구현했습니다.
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Presentation/ChattingRoomList/Coordinator/ChattingRoomListCoordinator.swift
  NearTalk/NearTalk/Presentation/ChattingRoomList/View/ChattingRoomListCell.swift
  NearTalk/NearTalk/Presentation/ChattingRoomList/View/ChattingRoomListViewController.swift
  NearTalk/NearTalk/Presentation/ChattingRoomList/ViewModel/ChattingRoomListViewModel.swift
Labels: feature

#61 [친구목록>UI구현] 친구 목록 기본 UI를 구현했습니다.
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Presentation/FriendsList/Coordinator/FriendsListCoordinator.swift
  NearTalk/NearTalk/Presentation/FriendsList/View/FriendsListCell.swift
  NearTalk/NearTalk/Presentation/FriendsList/View/FriendsViewController.swift
  NearTalk/NearTalk/Presentation/FriendsList/ViewModel/FriendsListModel.swift
  NearTalk/NearTalk/Presentation/FriendsList/ViewModel/FriendsListViewModel.swift
Labels: feature

#66 [런치스크린>파이어베이스 로그인] 파이어베이스 로그인 로직 구현
  .gitignore
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/AppDelegate.swift
  NearTalk/NearTalk/Application/DIContainer/LaunchScreenDIContainer.swift
  NearTalk/NearTalk/Application/SceneDelegate.swift
  NearTalk/NearTalk/Data/Repositories/DefaultLaunchScreenRepository.swift
  NearTalk/NearTalk/Domain/Entities/ChatMessage.swift
  NearTalk/NearTalk/Domain/Entities/ChatRoom.swift
  NearTalk/NearTalk/Domain/Entities/UserProfile.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/LaunchScreenRepository.swift
  NearTalk/NearTalk/Domain/UseCases/LaunchScreenUseCase.swift
  NearTalk/NearTalk/Infrastructure/Network/FireStoreService.swift
  NearTalk/NearTalk/Infrastructure/Network/FirebaseAuthService.swift
  NearTalk/NearTalk/Infrastructure/Network/RealTimeDatabaseService.swift
  NearTalk/NearTalk/Infrastructure/Network/StorageService.swift
  NearTalk/NearTalk/Infrastructure/Utils/NonceGenerator.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/Coordinator/LaunchScreenCoordinator.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/View/LaunchScreenViewController.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/ViewModel/LaunchScreenViewModel.swift
  NearTalk/Podfile
  NearTalk/Podfile.lock
Labels: feature

#68 [온보딩>UI구현] MVVM + C, Clean 아키텍처에 맞게 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/DIContainer/OnboardingDIContainer.swift
  NearTalk/NearTalk/Domain/Entities/UserProfile.swift
  NearTalk/NearTalk/Domain/UseCases/OnboardingUseCase.swift
  NearTalk/NearTalk/Infrastructure/Extensions/String+Regex.swift
  NearTalk/NearTalk/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  NearTalk/NearTalk/Presentation/Onboarding/View/OnboardingViewController.swift
  NearTalk/NearTalk/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: feature

#67 [채팅방생성>UI구현] 피드백 반영해서 다시 PR을 생성했습니다.
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Presentation/GroupChatCreation/View/GroupChatCreationViewController.swift
  NearTalk/NearTalk/Presentation/GroupChatCreation/View/RangeZoneView.swift
Labels: chore

#65 [메인지도>채팅방 마커] 채팅방 타입 별 Annotation 생성 및 Cluster Annotation 생성
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Presentation/MainMap/View/Components/ChatRoomAnnotation.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/ChatRoomClusterAnnotationView.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/DmChatRoomAnnotationView.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/GroupChatRoomAnnotationView.swift
  NearTalk/NearTalk/Presentation/MainMap/View/MainMapViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/ViewModel/DummyData/DummyData.plist
Labels: feature

#64 [친구프로필>프로필 상세UI구현] 프로필 상세화면 UI 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Presentation/ProfileDetail/View/ProfileDetailViewController.swift
Labels: feature

#70 [메인지도 > 오픈 채팅방 목록 Bottom sheet] 구현
  .gitattributes
  .gitignore
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/AppDelegate.swift
  NearTalk/NearTalk/Application/Coordinator/AppCoordinator.swift
  NearTalk/NearTalk/Application/Coordinator/LaunchScreenCoordinator.swift
  NearTalk/NearTalk/Application/DIContainer/LaunchScreenDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/OnboardingDIContainer.swift
  NearTalk/NearTalk/Application/SceneDelegate.swift
  NearTalk/NearTalk/Data/Repositories/DefaultLaunchScreenRepository.swift
  NearTalk/NearTalk/Domain/Entities/ChatMessage.swift
  NearTalk/NearTalk/Domain/Entities/ChatRoom.swift
  NearTalk/NearTalk/Domain/Entities/UserProfile.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/LaunchScreenRepository.swift
  NearTalk/NearTalk/Domain/UseCases/LaunchScreenUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/OnboardingUseCase.swift
  NearTalk/NearTalk/Infrastructure/Extensions/String+Regex.swift
  NearTalk/NearTalk/Infrastructure/Network/FireStoreService.swift
  NearTalk/NearTalk/Infrastructure/Network/FirebaseAuthService.swift
  NearTalk/NearTalk/Infrastructure/Network/RealTimeDatabaseService.swift
  NearTalk/NearTalk/Infrastructure/Network/StorageService.swift
  NearTalk/NearTalk/Infrastructure/Utils/NonceGenerator.swift
  NearTalk/NearTalk/Presentation/AppSetting/View/AppSettingTableViewCell.swift
  NearTalk/NearTalk/Presentation/AppSetting/View/AppSettingViewController.swift
  NearTalk/NearTalk/Presentation/ChattingRoomList/Coordinator/ChattingRoomListCoordinator.swift
  NearTalk/NearTalk/Presentation/ChattingRoomList/View/ChattingRoomListCell.swift
  NearTalk/NearTalk/Presentation/ChattingRoomList/View/ChattingRoomListViewController.swift
  NearTalk/NearTalk/Presentation/ChattingRoomList/ViewModel/ChattingRoomListViewModel.swift
  NearTalk/NearTalk/Presentation/ChattingRoomList/ViewModel/OpenChattingRoomListModel.swift
  NearTalk/NearTalk/Presentation/FriendsList/Coordinator/FriendsListCoordinator.swift
  NearTalk/NearTalk/Presentation/FriendsList/View/FriendsListCell.swift
  NearTalk/NearTalk/Presentation/FriendsList/View/FriendsViewController.swift
  NearTalk/NearTalk/Presentation/FriendsList/ViewModel/FriendsListModel.swift
  NearTalk/NearTalk/Presentation/FriendsList/ViewModel/FriendsListViewModel.swift
  NearTalk/NearTalk/Presentation/GroupChatCreation/View/GroupChatCreationViewController.swift
  NearTalk/NearTalk/Presentation/GroupChatCreation/View/RangeZoneView.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/Coordinator/LaunchScreenCoordinator.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/View/LaunchScreenViewController.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/ViewModel/LaunchScreenViewModel.swift
  NearTalk/NearTalk/Presentation/Login/View/LoginViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/Annotations/ChatRoomAnnotation.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/Annotations/ChatRoomClusterAnnotationView.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/Annotations/DmChatRoomAnnotationView.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/Annotations/GroupChatRoomAnnotationView.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/BottomSheet/BottomSheetTableViewCell/BottomSheetTableViewCell.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/BottomSheet/BottomSheetViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/View/MainMapViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/ViewModel/DummyData/DummyData.plist
  NearTalk/NearTalk/Presentation/MyProfile/View/MyProfileViewController.swift
  NearTalk/NearTalk/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  NearTalk/NearTalk/Presentation/Onboarding/View/OnboardingViewController.swift
  NearTalk/NearTalk/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/View/ProfileSettingViewController.swift
  NearTalk/Podfile
  NearTalk/Podfile.lock
Labels: feature

#78 [채팅방 목록>UI구현] RxSwift적용 및 fetch 분할작업
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Data/Repositories/ChatRoomListRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatRoomListRepository.swift
  NearTalk/NearTalk/Domain/Entities/ChatRoom.swift
  NearTalk/NearTalk/Domain/Entities/ChatRoomList.swift
  NearTalk/NearTalk/Domain/Entities/UserChatRoomModel.swift
  NearTalk/NearTalk/Domain/UseCases/ChatRoomListUseCase.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/Coordinator/ChatRoomListCoordinator.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListCell.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListViewController.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/ViewModel/ChatRoomListViewModel.swift
Labels: feature

#74 [프로필상세>VM/UseCase] ViewModel과 UseCase 구현했습니다.
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Domain/UseCases/ProfileDetailUseCase.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/Coordinator/ProfileDetailCoordinator.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/View/ProfileDetailViewController.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/ViewModel/ProfileDetailViewModel.swift
Labels: 리뷰요청, feature

#75 [채팅방생성>VM/UseCase구현] ViewModel과 UseCase 구현했습니다.
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Domain/UseCases/CreateGroupChatUseCase.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/Coordinator/CreateGroupChatCoordinator.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/View/GroupChatCreationViewController.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/View/RangeZoneView.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/ViewModel/CreateGroupChatViewModel.swift
Labels: 리뷰요청, feature

#81 Feat/byunghak/firebase
  NearTalk/.swiftlint.yml
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/Coordinator/AppCoordinator.swift
  NearTalk/NearTalk/Application/DIContainer/ChatRoomListDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/MyProfileDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/RootTabBarDIContainer.swift
  NearTalk/NearTalk/Application/SceneDelegate.swift
  NearTalk/NearTalk/Data/Repositories/DefaultTabBarRepository.swift
  NearTalk/NearTalk/Domain/Entities/NCLocation.swift
  NearTalk/NearTalk/Domain/Entities/UserChatModel.swift
  NearTalk/NearTalk/Domain/Entities/UserProfile.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/TabBarRepository.swift
  NearTalk/NearTalk/Domain/UseCases/TabBarUseCase.swift
  NearTalk/NearTalk/Infrastructure/Network/FireStoreService.swift
  NearTalk/NearTalk/Infrastructure/Network/FirebaseAuthService.swift
  NearTalk/NearTalk/Infrastructure/Network/FirebaseKey.swift
  NearTalk/NearTalk/Infrastructure/Network/RealTimeDatabaseService.swift
  NearTalk/NearTalk/Infrastructure/Network/StorageService.swift
  NearTalk/NearTalk/Presentation/MainMap/View/Components/BottomSheet/BottomSheetViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/View/MainMapViewController.swift
  NearTalk/NearTalk/Presentation/TabBar/Coordinator/RootTabBarCoordinator.swift
  NearTalk/NearTalk/Presentation/TabBar/View/RootTabBarController.swift
  NearTalk/NearTalk/Presentation/TabBar/ViewModel/RootTabBarViewModel.swift
  NearTalk/Podfile
  NearTalk/Podfile.lock
Labels: feature

#95 [네트워크] 파이어베이스 추상화
  NearTalk/GPSPoints/naver.gpx
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/Coordinator/AppCoordinator.swift
  NearTalk/NearTalk/Application/DIContainer/LaunchScreenDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/RootTabBarDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatRoomListRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultLaunchScreenRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultProfileRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultUserProfileRepository.swift
  NearTalk/NearTalk/Domain/DTO/FirebaseQueryDTO.swift
  NearTalk/NearTalk/Domain/Entities/BaseEntity.swift
  NearTalk/NearTalk/Domain/Entities/ChatMessage.swift
  NearTalk/NearTalk/Domain/Entities/ChatRoom.swift
  NearTalk/NearTalk/Domain/Entities/UserProfile.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/LaunchScreenRepository.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/ProfileRepository.swift
  NearTalk/NearTalk/Domain/UseCases/LaunchScreenUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/LoginUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/LogoutUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/OnboardingUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/VerifyUserUseCase.swift
  NearTalk/NearTalk/Infrastructure/Network/FireStoreService.swift
  NearTalk/NearTalk/Infrastructure/Network/FirebaseAuthService.swift
  NearTalk/NearTalk/Infrastructure/Network/FirebaseKey.swift
  NearTalk/NearTalk/Infrastructure/Network/FirebaseQueryKey.swift
  NearTalk/NearTalk/Infrastructure/Network/FirestoreService.swift
  NearTalk/NearTalk/Infrastructure/Network/RealTimeDatabaseService.swift
  NearTalk/NearTalk/Infrastructure/Network/StorageService.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListViewController.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/Coordinator/LaunchScreenCoordinator.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/View/LaunchScreenViewController.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/ViewModel/LaunchScreenViewModel.swift
  NearTalk/NearTalk/Presentation/TabBar/Coordinator/RootTabBarCoordinator.swift
Labels: refactor

#96 [앱설정->UseCase] LogoutUseCase, DropoutUseCase 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Data/Repositories/DefaultAuthRepository.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/AuthRepository.swift
  NearTalk/NearTalk/Domain/UseCases/DropOutUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/LogoutUseCase.swift
  NearTalk/NearTalk/Presentation/AppSetting/View/AppSettingTableViewCell.swift
  NearTalk/NearTalk/Presentation/AppSetting/View/AppSettingViewController.swift
Labels: feature

#101 [친구 목록] MVVM-C, Clean Architecture 적용했습니다.
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/DIContainer/ChatRoomListDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/FriendListDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/RootTabBarDIContainer.swift
  NearTalk/NearTalk/Domain/Entities/Friend.swift
  NearTalk/NearTalk/Domain/UseCases/FetchChatRoomUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/FetchFriendListUseCase.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListViewController.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/ViewModel/ChatRoomListViewModel.swift
  NearTalk/NearTalk/Presentation/FriendList/Coordinator/FriendListCoordinator.swift
  NearTalk/NearTalk/Presentation/FriendList/View/FriendListCell.swift
  NearTalk/NearTalk/Presentation/FriendList/View/FriendViewController.swift
  NearTalk/NearTalk/Presentation/FriendList/ViewModel/FriendListViewModel.swift
  NearTalk/NearTalk/Presentation/FriendsList/Coordinator/FriendsListCoordinator.swift
  NearTalk/NearTalk/Presentation/FriendsList/View/FriendsViewController.swift
  NearTalk/NearTalk/Presentation/FriendsList/ViewModel/FriendsListModel.swift
  NearTalk/NearTalk/Presentation/FriendsList/ViewModel/FriendsListViewModel.swift
  NearTalk/NearTalk/Presentation/TabBar/View/RootTabBarController.swift
Labels: feature

#102 [네트워킹] 파이어베이스 RealtimeDatabase를 활용해서 채팅 기능 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/Coordinator/AppCoordinator.swift
  NearTalk/NearTalk/Application/DIContainer/ChatRoomListDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/FriendListDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/LaunchScreenDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/OnboardingDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/RootTabBarDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/ChatRoomListRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultAuthRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatMessageRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatRoomListRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultMediaRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultProfileRepository.swift
  NearTalk/NearTalk/Domain/Entities/ChatRoom.swift
  NearTalk/NearTalk/Domain/Entities/UserChatRoomTicket.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/ChatMessageRepository.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/MediaRepository.swift
  NearTalk/NearTalk/Domain/UseCases/FetchChatRoomUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/LoginUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/UploadChatRoomInfoUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/VerifyUserUseCase.swift
  NearTalk/NearTalk/Infrastructure/Network/AuthService.swift
  NearTalk/NearTalk/Infrastructure/Network/FirebaseAuthService.swift
  NearTalk/NearTalk/Infrastructure/Network/FirebaseKey.swift
  NearTalk/NearTalk/Infrastructure/Network/FirestoreService.swift
  NearTalk/NearTalk/Infrastructure/Network/RealTimeDatabaseService.swift
  NearTalk/NearTalk/Infrastructure/Network/StorageService.swift
  NearTalk/NearTalk/NearTalk.entitlements
  NearTalk/NearTalk/Presentation/ChatRoomList/Coordinator/ChatRoomListCoordinator.swift
  NearTalk/NearTalk/Presentation/FriendList/Coordinator/FriendListCoordinator.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/ViewModel/LaunchScreenViewModel.swift
  NearTalk/NearTalk/Presentation/Login/View/LoginViewController.swift
  NearTalk/NearTalk/Presentation/MainMap/Coordinator/MainMapCoordinator.swift
  NearTalk/NearTalk/Presentation/TabBar/Coordinator/RootTabBarCoordinator.swift
  NearTalk/NearTalk/Presentation/TabBar/View/RootTabBarController.swift
Labels: feature

#108 [네트워킹] FCM Push notification 네트워킹
  .gitignore
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/AppDelegate.swift
  NearTalk/NearTalk/Application/Coordinator/AppCoordinator.swift
  NearTalk/NearTalk/Application/DIContainer/LaunchScreenDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/LoginDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/MyProfileDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/OnboardingDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/RootTabBarDIContainer.swift
  NearTalk/NearTalk/Data/Repositories/DefaultAuthRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultChatMessageRepository.swift
  NearTalk/NearTalk/Data/Repositories/DummyAuthRepository.swift
  NearTalk/NearTalk/Domain/DTO/FCMNotificationDTO.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/AuthRepository.swift
  NearTalk/NearTalk/Domain/Interfaces/Repositories/ChatMessageRepository.swift
  NearTalk/NearTalk/Domain/UseCases/DummyVerifyUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/UploadImageUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/VerifyUserUseCase.swift
  NearTalk/NearTalk/Infrastructure/Extensions/UIImage+Resize.swift
  NearTalk/NearTalk/Infrastructure/Network/FCMService.swift
  NearTalk/NearTalk/Infrastructure/Network/FirestoreService.swift
  NearTalk/NearTalk/Infrastructure/Utils/Environment.swift
  NearTalk/NearTalk/NearTalk.entitlements
  NearTalk/NearTalk/Presentation/LaucnScreen/Coordinator/LaunchScreenCoordinator.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/ViewModel/LaunchScreenViewModel.swift
  NearTalk/NearTalk/Presentation/Login/Coordinator/LoginCoordinator.swift
  NearTalk/NearTalk/Presentation/MyProfile/ViewModel/MyProfileViewModel.swift
  NearTalk/NearTalk/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  NearTalk/NearTalk/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/Coordinator/ProfileSettingCoordinator.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/View/ProfileSettingViewController.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/ViewModel/ProfileSettingViewModel.swift
  NearTalk/NearTalk/Presentation/TabBar/Coordinator/RootTabBarCoordinator.swift
  NearTalk/NearTalk/Resource/Info.plist
Labels: feature

#112 [DI] Swinject로 일부 DIContainer 구현
  .gitignore
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/Coordinator/AppCoordinator.swift
  NearTalk/NearTalk/Application/DIContainer/AppDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/LaunchScreenDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/LoginDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/OnboardingDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/RootTabBarDIContainer.swift
  NearTalk/NearTalk/Application/SceneDelegate.swift
  NearTalk/NearTalk/Data/Repositories/DefaultAuthRepository.swift
  NearTalk/NearTalk/Data/Repositories/DefaultTabBarRepository.swift
  NearTalk/NearTalk/Domain/UseCases/TabBarUseCase.swift
  NearTalk/NearTalk/Presentation/AppSetting/View/AppSettingViewController.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/Coordinator/CreateGroupChatCoordinator.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/Coordinator/LaunchScreenCoordinator.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/View/LaunchScreenViewController.swift
  NearTalk/NearTalk/Presentation/Login/Coordinator/LoginCoordinator.swift
  NearTalk/NearTalk/Presentation/Login/View/LoginViewController.swift
  NearTalk/NearTalk/Presentation/Login/ViewModel/LoginViewModel.swift
  NearTalk/NearTalk/Presentation/MyProfile/View/MyProfileViewController.swift
  NearTalk/NearTalk/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  NearTalk/NearTalk/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  NearTalk/NearTalk/Presentation/TabBar/Coordinator/RootTabBarCoordinator.swift
  NearTalk/NearTalk/Presentation/TabBar/View/RootTabBarController.swift
  NearTalk/Podfile
  NearTalk/Podfile.lock
Labels: feature

#111 Feature/신동은/채팅로직
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/DIContainer/ChatDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/ChatRoomListDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/CreateGroupChatDiContainer.swift
  NearTalk/NearTalk/Domain/UseCases/CreateGroupChatUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/Coordinator/ChatCoordinator.swift
  NearTalk/NearTalk/Presentation/Chat/MessagingUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatCollectionViewCell.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatViewController.swift
  NearTalk/NearTalk/Presentation/Chat/View/chatInputAccessoryView.swift
  NearTalk/NearTalk/Presentation/Chat/ViewModel/ChatViewModel.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/Coordinator/ChatRoomListCoordinator.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/ViewModel/ChatRoomListViewModel.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/Coordinator/CreateGroupChatCoordinator.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/View/GroupChatCreationViewController.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/View/RangeZoneView.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/ViewModel/CreateGroupChatViewModel.swift
Labels: feature, fix

#116 [채팅] 체팅 송수신 UI 개선 및 MessagingUseCase 구현
  NearTalk/NearTalk/Application/DIContainer/ChatDIContainer.swift
  NearTalk/NearTalk/Presentation/Chat/MessagingUseCase.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatCollectionViewCell.swift
  NearTalk/NearTalk/Presentation/Chat/View/ChatViewController.swift
  NearTalk/NearTalk/Presentation/Chat/ViewModel/ChatViewModel.swift
  NearTalk/NearTalk/Presentation/CreatGroupChat/ViewModel/CreateGroupChatViewModel.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/FetchProfileUseCase.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/RemoveFriendUseCase.swift
  NearTalk/NearTalk/Presentation/ProfileDetail/ViewModel/ProfileDetailViewModel.swift
Labels: feature, fix

#115 [앱설정] 로그아웃, 탈퇴, 앱 알림 On/Off, 프로필 사진 불러올 때 Crop 기능 구현
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/Coordinator/AppCoordinator.swift
  NearTalk/NearTalk/Application/DIContainer/AppDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/AppSettingDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/MyProfileDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/OnboardingDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/RootTabBarDIContainer.swift
  NearTalk/NearTalk/Domain/UseCases/DropOutUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/LogoutUseCase.swift
  NearTalk/NearTalk/Infrastructure/Network/FirestoreService.swift
  NearTalk/NearTalk/Presentation/AppSetting/Coordinator/AppSettingCoordinator.swift
  NearTalk/NearTalk/Presentation/AppSetting/View/AppSettingTableViewCell.swift
  NearTalk/NearTalk/Presentation/AppSetting/View/AppSettingViewController.swift
  NearTalk/NearTalk/Presentation/AppSetting/ViewModel/AppSettingViewModel.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/View/LaunchScreenViewController.swift
  NearTalk/NearTalk/Presentation/MyProfile/Coordinator/MyProfileCoordinator.swift
  NearTalk/NearTalk/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  NearTalk/NearTalk/Presentation/Onboarding/View/OnboardingViewController.swift
  NearTalk/NearTalk/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/Coordinator/ProfileSettingCoordinator.swift
  NearTalk/NearTalk/Presentation/ProfileSetting/View/ProfileSettingViewController.swift
  NearTalk/NearTalk/Presentation/TabBar/Coordinator/RootTabBarCoordinator.swift
Labels: bug, feature

#117 [친구목록/ 친구목록] 채팅방 목록 기능 추가, 친구목록 기능 추가 및 UI 업데이트
  NearTalk/NearTalk.xcodeproj/project.pbxproj
  NearTalk/NearTalk/Application/DIContainer/ChatRoomListDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/FriendListDIContainer.swift
  NearTalk/NearTalk/Domain/Entities/ChatRoomList.swift
  NearTalk/NearTalk/Domain/UseCases/FetchChatRoomUseCase.swift
  NearTalk/NearTalk/Domain/UseCases/FetchFriendListUseCase.swift
  NearTalk/NearTalk/Infrastructure/Utils/PaddingLabel.swift
  NearTalk/NearTalk/Presentation/Chat/ViewModel/ChatViewModel.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/Coordinator/ChatRoomListCoordinator.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListCell.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/View/ChatRoomListViewController.swift
  NearTalk/NearTalk/Presentation/ChatRoomList/ViewModel/ChatRoomListViewModel.swift
  NearTalk/NearTalk/Presentation/FriendList/View/FriendListCell.swift
  NearTalk/NearTalk/Presentation/FriendList/View/FriendViewController.swift
  NearTalk/NearTalk/Presentation/FriendList/ViewModel/FriendListViewModel.swift
  NearTalk/NearTalk/Presentation/LaucnScreen/Base.lproj/LaunchScreen.storyboard
  NearTalk/NearTalk/Presentation/ProfileDetail/Coordinator/ProfileDetailCoordinator.swift
  NearTalk/NearTalk/Presentation/TabBar/Coordinator/RootTabBarCoordinator.swift
  NearTalk/NearTalk/Presentation/ViewController.swift
Labels: feature, fix

#118 [앱설정>알림] 푸쉬 알림 안 오는 버그 픽스 및 메서드 네이밍 변경
  NearTalk/NearTalk/Application/AppDelegate.swift
  NearTalk/NearTalk/Application/Coordinator/AppCoordinator.swift
  NearTalk/NearTalk/Application/DIContainer/AppDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/AppSettingDIContainer.swift
  NearTalk/NearTalk/Application/DIContainer/RootTabBarDIContainer.swift
  NearTalk/NearTalk/Domain/UseCases/DropOutUseCase.swift
  NearTalk/NearTalk/Presentation/AppSetting/View/AppSettingViewController.swift
  NearTalk/NearTalk/Presentation/AppSetting/ViewModel/AppSettingViewModel.swift
Labels: chore, fix
